### PR TITLE
Pull request Positioning and Floating Elements project

### PR DESCRIPTION
**Pull request by nriqu322**
We clone the NYT article and used Float, positioning and offset properties to develop this project.

### CODE REVIEW

**Comment by euqueme** [comment]
Pull Request under the review by Maria Eugenia Quemé P. (TSE)

**Comment by euqueme** [comment]
> Pull Request under the review by Maria Eugenia Quemé P. (TSE)

## Hello @nriqu322  and @bren2102  :handshake: 
### This is an impressive work :medal_sports: just a few things to work on before we can give you the approval:

**Bottom part**

- [x] It contains links to **most popular** articles on the rightmost side: you are missing the \<a\> tags ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**Footer**

- [x] The background color should be white and it has to have a black border-top, also the text should be more centered like the original :arrow_double_down: 

image

**Linters**

- [x] I noticed your Linters aren't working perhaps because you haven't activated the project on [stickler](https://stickler-ci.com/)

**Live Demo**

- [x] Follow these [steps](https://help.github.com/en/enterprise/2.13/user/articles/configuring-a-publishing-source-for-github-pages) to generate a Live Demo of your project and include it in your Readme file

### That's it. Please :pray: correct these changes and submit back for a code review when you are done :rocket:

#### Happy Coding! :woman_technologist:

**Comment by nriqu322** [comment]
Hello Maria Eugenia, thank you for your observations. 
All in your checklist has been fixed.

**Review by suretrust — APPROVED** [review]
Hi team, 👋 

### Great job, I can see you have implemented the TSE's suggestions. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

**Pull request merged**
